### ISSUE TITLE
不能生成字幕文件

### ISSUE THREAD

**Issue by jkguo-creator** [zcf0508/autocut-client#20]
#### Describe the problem you confuse
安装完成，拖拉视频文件进入软件，只生成音频文件，没有生成字幕文件

**Comment by zcf0508** [comment]
@jkguo-creator 有生成字幕的进度显示吗？

**Comment by jkguo-creator** [comment]
> @jkguo-creator 有生成字幕的进度显示吗？

没有进度，只生成音频

**Comment by jkguo-creator** [comment]
生成的时候字幕进度好像没有，然后生成好音频就自动关闭了

**Comment by zcf0508** [comment]
自动关闭是指程序自动退出了吗？

你如果方便的话，可以在 autocut-client 的可执行目录空白处，shift+右键然后选择「在此处打开 Powershell 窗口」，在窗口中输入 `./autocut-client.exe`


```shell
PS path\to\client> ./autocut-client.exe
```

然后提交一下输出的内容

**Comment by jkguo-creator** [comment]
``Error: ENOENT: no such file or directory, open 'D:\autocut\source\test.srt'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Module.readFileSync (node:fs:453:35)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9156)
    at o (index.5e58f2a3.js:45:52181)
    at setup (index.5e58f2a3.js:45:52343)
    at Xt (index.5e58f2a3.js:1:14468)
    at Mm (index.5e58f2a3.js:1:61778)
    at rd (index.5e58f2a3.js:1:61563)
    at ie (index.5e58f2a3.js:1:49082)

**Comment by jkguo-creator** [comment]
> 自动关闭是指程序自动退出了吗？
> 
> 你如果方便的话，可以在 autocut-client 的可执行目录空白处，shift+右键然后选择「在此处打开 Powershell 窗口」，在窗口中输入 `./autocut-client.exe`
> 
> ```shell
> PS path\to\client> ./autocut-client.exe
> ```
> 
> 正常操作后，提交一下输出的内容
tijiao

**Comment by jkguo-creator** [comment]
> 自动关闭是指程序自动退出了吗？
> 
> 你如果方便的话，可以在 autocut-client 的可执行目录空白处，shift+右键然后选择「在此处打开 Powershell 窗口」，在窗口中输入 `./autocut-client.exe`
> 
> ```shell
> PS path\to\client> ./autocut-client.exe
> ```
> 
> 正常操作后，提交一下输出的内容

>正常启动

**Comment by jkguo-creator** [comment]
stderr: None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
stderr: [autocut:transcribe.py:L38] INFO   Transcribing D:\\autocut\\autocut-client\\source\\test.wav
stderr: torchaudio\backend\utils.py:62: UserWarning: No audio backend is available.
stderr:   warnings.warn("No audio backend is available.")
stderr: Traceback (most recent call last):
stderr:   File "autocut.py", line 6, in <module>
stderr:   File "autocut\main.py", line 96, in main
stderr:   File "autocut\transcribe.py", line 49, in run
stderr:   File "autocut\transcribe.py", line 66, in _detect_voice_activity
stderr:   File "torch\hub.py", line 542, in load
stderr:   File "torch\hub.py", line 572, in _load_local
stderr:   File "D:\autocut\autocut\snakers4_silero-vad_master\hubconf.py", line 38, in silero_vad
stderr:     model = init_jit_model(model_path=f'{hub_dir}/snakers4_silero-vad_master/files/silero_vad.jit')
stderr:   File "D:\autocut\autocut\snakers4_silero-vad_master\utils_vad.py", line 146, in init_jit_model
stderr:     model = torch.jit.load(model_path, map_location=device)
stderr:   File "torch\jit\_serialization.py", line 152, in load
stderr: ValueError: The provided filename C:\Users\xmblt/.cache\torch\hub/snakers4_silero-vad_master/files/silero_vad.jit does not exist
stderr: [3384] Failed to execute script 'autocut' due to unhandled exception!

**Comment by jkguo-creator** [comment]
gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by zcf0508** [comment]
好的，我排查一下，谢谢反馈

**Comment by jkguo-creator** [comment]
3和4都不行，是不是python版本问题，我是安装3.8.6

**Comment by jkguo-creator** [comment]
另外一个问题是GPU驱动，是不是GPU驱动问题也影响了

**Comment by zcf0508** [comment]
https://github.com/zcf0508/autocut-client/releases/tag/v0.0.7

下载新版安装，再重装一下 AutoCut ，然后试下。

暂时不支持使用 GPU ，需要使用 GPU 的话可以下载李沐老师的 python 版本来生成字幕。

**Comment by jkguo-creator** [comment]
> https://github.com/zcf0508/autocut-client/releases/tag/v0.0.7
> 
> 下载新版安装，再重装一下 AutoCut ，然后试下。
> 
> 暂时不支持使用 GPU ，需要使用 GPU 的话可以下载李沐老师的 python 版本来生成字幕。

>新版有字幕进度应该可以了，我试试完整的操作，谢谢哈

**Comment by jkguo-creator** [comment]
非常感谢



在 2023-01-12 23:00:35，"周财发" ***@***.***> 写道：

https://github.com/zcf0508/autocut-client/releases/tag/v0.0.7

下载新版安装，再重装一下 AutoCut ，然后试下。

暂时不支持使用 GPU ，需要使用 GPU 的话可以下载李沐老师的 python 版本来生成字幕。
