### ISSUE TITLE
建议加个srt字幕文件选项，省去自动生成字幕缓慢的问题

### ISSUE THREAD

**Issue by 1353604736** [zcf0508/autocut-client#28]

**Comment by zcf0508** [comment]
视频目录下有同名srt文件的话应该是会自动跳过识别字幕过程的。

**Comment by zcf0508** [comment]
我自己测试是可以的，方便看下你的目录结构吗？

**Comment by 1353604736** [comment]
> 我自己测试是可以的，方便看下你的目录结构吗？

测试了一下 是可以的，下划线和空格看错了

**Comment by 1353604736** [comment]
在有字幕文件情况下，提示生成字幕中
![2023-2-14 23-30-17](https://user-images.githubusercontent.com/12869582/218783305-6d09dd7d-16a3-4912-ae2e-abfa019f56e1.png)

**Comment by zcf0508** [comment]
https://github.com/zcf0508/autocut-client/releases/tag/v0.1.3

已更新
