### ISSUE TITLE
导出视频在哪里

### ISSUE THREAD

**Issue by linchen111** [zcf0508/autocut-client#30]
导出的视频是剪辑完成的视频吗？ 找不到文件在哪

**Comment by zcf0508** [comment]
源文件同级目录下，文件名为  `原文件名_cut.mp4`

**Comment by linchen111** [comment]
> 我所使用的为autocut-client_v0.1.3.exe，导出视频后只有 原文件名_cut.srt文件，不知道什么原因呢

**Comment by zcf0508** [comment]
生成会比较花时间，生成完成应该会有个弹窗提醒。

**Comment by linchen111** [comment]
确实存在弹窗，“导出成功 close”。但是就是没有cut后的mp4，这是否和我什么没有安装成功有关

**Comment by zcf0508** [comment]
调用的是这个库里的这个部分，你可以试一下直接在 autocut 安装包的目录下执行这个剪辑命令试试。

https://github.com/mli/autocut#%E5%89%AA%E5%88%87%E6%9F%90%E4%B8%AA%E8%A7%86%E9%A2%91

**Comment by linchen111** [comment]
直接调用发现是有效的。但有个问题就是cut后的视频是连续的，但是字幕的时间轴不连续，也就是字幕的时间比较长（剪辑前视频长），中间有许多gap。请问您了解怎么批量删除他们吗，波纹删除似乎只能一个一个点
