### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by keen0309** [zcf0508/autocut-client#42]
默认全部勾选，我想默认全部不勾选怎么办呢

**Comment by henglei1228** [comment]
您的邮件已收到！谢谢。

**Comment by keen0309** [comment]
> 您的邮件已收到！谢谢。

默认全部勾选。我想不勾选。
![image](https://github.com/zcf0508/autocut-client/assets/103982843/3fbd2a5d-662b-46b8-afee-6f1f2962a44b)

**Comment by zcf0508** [comment]
https://github.com/zcf0508/autocut-client/issues/43
