### ISSUE TITLE
希望可以批量选中字幕

### ISSUE THREAD

**Issue by keen0309** [zcf0508/autocut-client#43]
希望可以批量选中字幕，一个一个点太麻烦，还有就是增加两个选项一个默认全部勾选字幕一个默认不勾选

**Comment by zcf0508** [comment]
好的👌

**Comment by keen0309** [comment]
> 好的👌

大神您好，什么时候可以加好。我可以付费。。。。

**Comment by zcf0508** [comment]
https://github.com/zcf0508/autocut-client/releases/tag/v0.1.6
