### ISSUE TITLE
求助，显示导出成功，但是找不到导出视频，请问导出的视频存放在哪里，没有在视频当前目录找到

### ISSUE THREAD

**Issue by codexiaoyu** [zcf0508/autocut-client#65]
求助，显示导出成功，但是找不到导出视频，请问导出的视频存放在哪里，没有在视频当前目录找到
![微信截图_20240](https://github.com/zcf0508/autocut-client/assets/53516546/742081bc-43fc-4e0f-a650-6f5a1d640716)

**Comment by henglei1228** [comment]
您的邮件已收到！谢谢。

**Comment by zcf0508** [comment]
- 原视频.mp4
- 原视频.srt   <- 识别的完整字幕文件
- 原视频.wav  <- 视频中提取的音频文件
- 原视频_cut_时间戳.srt  <- 编辑后的字幕
- 原视频_cut_时间戳.mp4  <- 根据编辑后的字幕生成的视频

以上所有的文件都和原视频在同一级文件夹下。
