### ISSUE TITLE
macOS 10.15.7 路径识别问题

### ISSUE THREAD

**Issue by kerwinfang** [zcf0508/autocut-client#69]
![WX20240427-211751](https://github.com/zcf0508/autocut-client/assets/16949624/aa1cd50d-d384-4339-a1e0-4f6c7cd5d73a)

**Comment by henglei1228** [comment]
您的邮件已收到！谢谢。

**Comment by change3799** [comment]
Have you found a solution?

**Comment by henglei1228** [comment]
您的邮件已收到！谢谢。

**Comment by change3799** [comment]
> 您的邮件已收到！谢谢。

I also have the same problem, how should I solve it?

**Comment by zcf0508** [comment]
https://github.com/zcf0508/autocut-client/releases/tag/v0.1.11

**Comment by change3799** [comment]
> https://github.com/zcf0508/autocut-client/releases/tag/v0.1.11

Updated to the latest Mac version available. "autocut-client.app" is corrupted and cannot be opened. You should move it to the Trash. "

**Comment by zcf0508** [comment]
> Updated to the latest Mac version available. "autocut-client.app" is corrupted and cannot be opened. You should move it to the Trash. "

Thanks for your report. I downgrade macos version to `macos-12` since the `macos-latest` [is based on the ARM architecture](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md).

**Comment by change3799** [comment]
> > 已更新至最新的Mac版本。“autocut-client.app”已损坏，无法打开。您应该将其移至废纸篓。”
> 
> 感谢您的报告。我将 macos 版本降级为，`macos-12`因为它`macos-latest` [基于 ARM 架构](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md)。

Yes, I am arm M1, the version is 14.3 and the problem just occurred.

**Comment by change3799** [comment]
> > 已更新至最新的 Mac 版本。“autocut-client.app”已损坏，无法打开。您应该将其移至废纸篓。"
> 
> 感谢您的报告。我将 macos 版本降级为 ，`macos-12`因为它`macos-latest` [基于 ARM 架构](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md)。

I don't know why. I downloaded and installed and still have the problem as shown in the picture. Did I do something wrong?

> ![WX20240427-211751](https://private-user-images.githubusercontent.com/16949624/326180511-aa1cd50d-d384-4339-a1e0-4f6c7cd5d73a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzE2MDcsIm5iZiI6MTcyOTY3MTMwNywicGF0aCI6Ii8xNjk0OTYyNC8zMjYxODA1MTEtYWExY2Q1MGQtZDM4NC00MzM5LWExZTAtNGY2YzdjZDVkNzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MjkwZmUyYTkwYmFiN2Q4YTBhODA3NjRkYmJiOTFmMGRlYjJlZWE0NzY0OWFlNjA1ZjdjNzY1ZmNmYTgwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fVzHSaU0VZw6PsouwNdsTUSlWd7Etoh0jt1PsnG0kOs)

**Comment by change3799** [comment]
> > > 已更新至最新的Mac版本。“autocut-client.app”已损坏，无法打开。您应该将其移至废纸篓。”
> > 
> > 
> > 感谢您的报告。我将 macos 版本降级为，`macos-12`因为它`macos-latest` [基于 ARM 架构](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md)。
> 
> 是的，我是arm M1，版本是14.3，刚刚出现这个问题。

Do I need to fix this issue to use it normally?
![Uploading Screenshot2024-10-23 16.25.56.png…]()

**Comment by change3799** [comment]
> > Updated to the latest Mac version available. "autocut-client.app" is corrupted and cannot be opened. You should move it to the Trash. "
> 
> Thanks for your report. I downgrade macos version to `macos-12` since the `macos-latest` [is based on the ARM architecture](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md).

Do I need to fix this issue to use it normally?
<img width="1418" alt="Screenshot2024-10-23 16 25 56" src="https://github.com/user-attachments/assets/a5473718-e74a-437f-8e9a-0fdcd27a904c">
