### ISSUE TITLE
是否可以支持选择md字幕文件的输入，及基于md文件的视屏输出？

### ISSUE THREAD

**Issue by shnsvyu** [zcf0508/autocut-client#70]
是否可以支持选择md字幕文件的输入，及基于md文件的视屏输出？

![微信图片_20240728044420](https://github.com/user-attachments/assets/e621bf0b-20e5-4f61-b48d-97715ea691d5)

**Comment by henglei1228** [comment]
您的邮件已收到！谢谢。

**Comment by shnsvyu** [comment]
解决了，忽略吧，谢谢
